### ISSUE TITLE
Get definition for multiple use is failing for all but the first one

### ISSUE THREAD

**Issue by albertored** [elixir-lsp/elixir_sense#175] opened 2023-02-02 08:41 UTC
I'm not able to get the definition for modules `use`d like that:
```elixir
defmodule A do
  use B.{C, D}
end
```
`C` definition is correctly found while `D` is not.

A failing test is worth more than a thousand words: https://github.com/albertored/elixir_sense/commit/a075a70ce0b4757ec7773ee7805b3cd215c8823c

**Comment by lukaszsamson** [comment] 2023-04-23 11:49
Duplicate of https://github.com/elixir-lsp/elixir_sense/issues/211

**Closed by lukaszsamson** 2023-04-23 11:49 UTC
Labels: bug
