### ISSUE TITLE
Exception raised in ecto plugin

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir_sense#110] opened 2020-09-03 21:01 UTC
I'm getting the following exception and similar fairly regularly when writing a ecto query:
```
Company: backend company-capf error "an exception was raised:
    ** (FunctionClauseError) no function clause matching in :elixir_env.trace/2
        (elixir 1.10.4) src/elixir_env.erl:35: :elixir_env.trace({:alias_reference, [line: 1], User}, #Macro.Env<aliases: [], context: nil, context_modules: [], file: "nofile", function: nil, functions: [], lexical_tracker: nil, line: 0, macro_aliases: [], macros: [], module: nil, requires: [], ...>)
        (elixir 1.10.4) lib/macro.ex:1384: Macro.do_expand_once/2
        (elixir 1.10.4) lib/macro.ex:1369: Macro.expand_once/2
        (elixir_sense 1.0.1) lib/elixir_sense/plugins/ecto/query.ex:192: ElixirSense.Plugins.Ecto.Query.infer_type/4
        (elixir_sense 1.0.1) lib/elixir_sense/plugins/ecto/query.ex:226: anonymous fn/4 in ElixirSense.Plugins.Ecto.Query.extract_bindings/4
        (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir_sense 1.0.1) lib/elixir_sense/plugins/ecto.ex:87: ElixirSense.Plugins.Ecto.suggestions/4
        (elixir_sense 1.0.1) lib/elixir_sense/providers/suggestion/generic_reducer.ex:39: ElixirSense.Providers.Suggestion.GenericReducer.reduce/6" with args (candidates achi)
```
My project is on:
```
erlang 22.3.4.3
elixir 1.10.4-otp-22
```

**Comment by lukaszsamson** [comment] 2020-09-03 21:10
Could you add a log and post what is the crashing ast in `lib/elixir_sense/plugins/ecto/query.ex:192`?

**Comment by axelson** [comment] 2020-10-03 20:42
Unfortunately I haven't been able to reproduce this on other projects yet, so I'm not sure what causes it.

**Comment by akashkhan25** [comment] 2020-10-06 13:39
I had the same issue on all my projects after updating to the latest version.

The following is the log from a fresh new phoenix project with one schema

Project details
```
Elixir version: 1.10.1
Erlang version: 23.0.2
```

```
21:32:00.442 [error] Process #PID<0.536.0> raised an exception
** (FunctionClauseError) no function clause matching in :elixir_env.trace/2
    (elixir 1.10.1) src/elixir_env.erl:35: :elixir_env.trace({:alias_reference, [line: 1], TestApp}, #Macro.Env<aliases: [], context: nil, context_modules: [], file: "nofile", function: nil, functions: [], lexical_tracker: nil, line: 0, macro_aliases: [], macros: [], module: nil, requires: [], ...>)
    (elixir 1.10.1) lib/macro.ex:1384: Macro.do_expand_once/2
    (elixir 1.10.1) lib/macro.ex:1369: Macro.expand_once/2
    (elixir_sense 1.0.1) lib/elixir_sense/plugins/ecto/query.ex:193: ElixirSense.Plugins.Ecto.Query.infer_type/4
    (elixir_sense 1.0.1) lib/elixir_sense/plugins/ecto/query.ex:227: anonymous fn/4 in ElixirSense.Plugins.Ecto.Query.extract_bindings/4
    (elixir 1.10.1) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir_sense 1.0.1) lib/elixir_sense/plugins/ecto.ex:87: ElixirSense.Plugins.Ecto.suggestions/4
    (elixir_sense 1.0.1) lib/elixir_sense/providers/suggestion/generic_reducer.ex:39: ElixirSense.Providers.Suggestion.GenericReducer.reduce/6
{:__aliases__, [line: 1], [:TestApp]}
[Error  - 9:32:02 PM] Request textDocument/completion failed.
  Message: an exception was raised:
    ** (FunctionClauseError) no function clause matching in :elixir_env.trace/2
        (elixir 1.10.1) src/elixir_env.erl:35: :elixir_env.trace({:alias_reference, [line: 1], TestApp}, #Macro.Env<aliases: [], context: nil, context_modules: [], file: "nofile", function: nil, functions: [], lexical_tracker: nil, line: 0, macro_aliases: [], macros: [], module: nil, requires: [], ...>)
        (elixir 1.10.1) lib/macro.ex:1384: Macro.do_expand_once/2
        (elixir 1.10.1) lib/macro.ex:1369: Macro.expand_once/2
        (elixir_sense 1.0.1) lib/elixir_sense/plugins/ecto/query.ex:193: ElixirSense.Plugins.Ecto.Query.infer_type/4
        (elixir_sense 1.0.1) lib/elixir_sense/plugins/ecto/query.ex:227: anonymous fn/4 in ElixirSense.Plugins.Ecto.Query.extract_bindings/4
        (elixir 1.10.1) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir_sense 1.0.1) lib/elixir_sense/plugins/ecto.ex:87: ElixirSense.Plugins.Ecto.suggestions/4
        (elixir_sense 1.0.1) lib/elixir_sense/providers/suggestion/generic_reducer.ex:39: ElixirSense.Providers.Suggestion.GenericReducer.reduce/6
  Code: -32000 
```
The crashing AST is `{:__aliases__, [line: 1], [:TestApp]}` and `User` is the ecto schema

**Comment by msaraiva** [comment] 2020-10-08 16:04
Hi @akashkhan25 and @axelson!

I can't reproduce it but https://github.com/elixir-lsp/elixir_sense/commit/36e3ff7bebd4b59a15a864babec1385028a7e2c0 should do the trick. Can any of you try that out and confirm it works?

**Comment by lukaszsamson** [comment] 2021-11-07 09:07
Seems the issue is now fixed

**Closed by lukaszsamson** 2021-11-07 09:07 UTC
